spring.application.name=image-microservice

cloudinary.cloud-name=dwupsqa4m
cloudinary.api-key=966156156862629
cloudinary.api-secret=OevIZKoSVW1oYIYGZo-DYbId0uk

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/armory-realm

logging.level.org.springframework.security=DEBUG

server.port=8080

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

# Rabbit mq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Roles
security.roles.admin=system-admin
security.roles.manager=inventory-manager
security.roles.soldier=soldier
security.roles.public-access=public-access