spring.application.name=user-microservice

server.port=8080

spring.cloud.config.enabled=false

spring.mongodb.uri=mongodb://mongo:rQJgocBNtfJFmWmMXnwupmhjoKHAQkHZ@acela.proxy.rlwy.net:53936/locations?authSource=admin

# KEYCLOAK (RESOURCE SERVER)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak-production-d501.up.railway.app/realms/armory-realm

# Logging opcional
logging.level.org.springframework.security=DEBUG

eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://discovery-service.railway.internal:8761/eureka

# Rabbit mq
spring.rabbitmq.host=rabbitmq.railway.internal
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Roles
security.roles.admin=system-admin
security.roles.manager=inventory-manager
security.roles.soldier=soldier
security.roles.public-access=public-access